#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.
puts "Compiling"

dirname = "."

filename = ARGV[0]

Dir.chdir(dirname)

puts "#{filename}.s"

splitFilename = filename.split("/")
getFileName   = splitFilename[splitFilename.length - 1]
file = getFileName.split(".wacc")[0]

puts file 


`touch "#{file}.s"`


output = `stack exec WACC-HASKELL #{filename}`
exitCode = $?.exitstatus

`echo "#{output}" >> "#{file}.s"` 
puts "Compilation Done"

exit (exitCode)
