#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.
puts "Compiling"

dirname = "."

filename = ARGV[0]

Dir.chdir(dirname)

splitFilename = filename.split("/")
getFileName   = splitFilename[splitFilename.length - 1]
file = getFileName.split(".wacc")[0]

output = `stack exec WACC-HASKELL  #{filename}`
exitCode = $?.exitstatus

#out_file = File.new(file + ".s", "w")
#
#out_file.puts(output)
#out_file.close

puts output

exit (exitCode)
