#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.
puts "Compiling"

filename = ARGV[0]

output  = `cabal run WACC-HASKELL #{filename}`
puts output

puts "Compilation Done"
